#! /usr/bin/env dash

# https://universal-blue.discourse.group/t/setting-up-a-distrobox/44#p-50-using-the-hosts-xdg-open-inside-distrobox-4

if [ ! -e /run/.containerenv ] && [ ! -e /.dockerenv ]
then
    /usr/bin/xdg-open "$@"
else
    distrobox-host-exec /usr/bin/xdg-open "$@"
fi
